# Generated by Django 3.2.6 on 2022-07-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_of_feed', models.URLField()),
                ('feed_name', models.CharField(max_length=200)),
            ],
        ),
    ]
