# Generated by Django 3.2.6 on 2022-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
