# Generated by Django 3.2.6 on 2022-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_episode_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(max_length=100),
        ),
    ]
